import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import ReactQueryProvider from './chat/components/react-query-provider'
import { TooltipProvider } from '@/components/ui/tooltip'
import { Toaster } from 'sonner';
import Navbar from "@/components/ui/navbar"
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ReactQueryProvider>
    <TooltipProvider>
      <html lang="en">
        <body className={inter.className}>
          <Navbar />
          {children}
          <Toaster />
        </body>
      </html>
      </TooltipProvider>
    </ReactQueryProvider>
  )
}
